import numpy as np
from scipy.linalg import null_space

# do we even need the k_maps? couldn't that be removed? 

def dot(a,b):
    # a dot product on matricies with one column
    return np.sum(np.multiply(a,b))

def matrix_equals(A, B):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i, j] != B[i, j]:
                return False
    return True

class PhaseSpace:
    def __init__(self, t_vect_perp, k_vect_perp):
        self.vect_dim = t_vect_perp.shape[0]
        self.phase_space_dim = 2*(self.vect_dim-1)
        self.t_vect_perp = t_vect_perp
        self.k_vect_perp = k_vect_perp
        self.t_basis = null_space(t_vect_perp.reshape(1, -1))  # shape (vect_dim, vect_dim-1)
        self.k_basis = null_space(k_vect_perp.reshape(1, -1))  # shape (v  ect_dim, vect_dim-1)
        # the phase space is not just the null space. But rather it's an affine space, generated by the null space and adding
        # t_vect_perp/<t_vect_perp,t_vect_perp>
        self.t_transition_inverse = np.linalg.inv(np.matrix(self.t_basis.T @ self.t_basis))
        self.k_transition_inverse = np.linalg.inv(np.matrix(self.k_basis.T @ self.k_basis))
        self.t_offset = self.t_vect_perp/dot(self.t_vect_perp, self.t_vect_perp)
        self.k_offset = self.k_vect_perp/dot(self.k_vect_perp, self.k_vect_perp)

    def to_phase_space_coordinates(self, t_vect, k_vect):
        # Here we can pretend that the phase space is a subspace and not an affine space.
        return np.concatenate([self.t_transition_inverse @ self.t_basis.T @ t_vect, self.k_transition_inverse @ self.k_basis.T @ k_vect])

    def from_phase_space_coordinates(self, x):
        return self.t_basis @ x[:self.phase_space_dim//2] + self.t_offset, self.k_basis @ x[self.phase_space_dim//2:] + self.k_offset
    
    def map_id_x_phi_T(self, new_K_normal_vect):
        # <new_K_normal_vect, x - lambda self.t_vect_perp> = 1
        # x mapsto -lambda(x) self.t_vect_perp + x
        # where lambda(x) = <new_K_normal_vect,x>/s - 1/s
        # This means K_shift = self.t_vect_perp/s
        # and K_matrix = I - A
        # where A = [[self.t_vect_perp_1/s new_K_normal_vect^T]
        #            [...]
        #            [self.t_vect_perp_self.vect_dim/s new_K_normal_vect^T]]
        # where s = <new_K_normal_vect,self.t_vect_perp>
        s = dot(new_K_normal_vect, self.t_vect_perp)
        if(s == 0):
            raise ValueError("new_K_normal_vect and self.t_vect_perp are perpendicular")
        K_shift = self.t_vect_perp/s
        A = np.outer(self.t_vect_perp, new_K_normal_vect)/s
        K_matrix = np.eye(self.vect_dim) - A
        output_phase_space = PhaseSpace(t_vect_perp=self.t_vect_perp,k_vect_perp=new_K_normal_vect)
        return PhaseSpaceMap(
            input_phase_space=self,
            output_phase_space=output_phase_space,
            T_matrix=np.eye(self.vect_dim),
            K_matrix=K_matrix,
            T_shift=np.zeros((self.vect_dim, 1)),
            K_shift=K_shift
        )
    
    def map_phi_K_x_id(self, new_T_normal_vect):
        # <new_T_normal_vect, x + lambda(x) self.k_vect_perp> = 1
        # x mapsto lambda(x) self.k_vect_perp + x
        # where s*lambda(x) + <new_T_normal_vect,x> = 1
        #         lambda(x) = -<new_T_normal_vect,x>/s + 1/s
        # This means T_shift = self.k_vect_perp/s
        # and T_matrix = I - A
        # where A = [[self.k_vect_perp_1/s new_T_normal_vect^T]
        #            [...]
        #            [self.k_vect_perp_self.vect_dim/s new_T_normal_vect^T]]
        # where s = <new_T_normal_vect,self.k_vect_perp>
        s = dot(new_T_normal_vect, self.k_vect_perp)
        if(s == 0):
            raise ValueError("new_T_normal_vect and self.k_vect_perp are perpendicular")
        T_shift = self.k_vect_perp/s
        A = np.outer(self.k_vect_perp, new_T_normal_vect)/s
        T_matrix = np.eye(self.vect_dim) - A
        output_phase_space = PhaseSpace(t_vect_perp=new_T_normal_vect,k_vect_perp=self.k_vect_perp)
        return PhaseSpaceMap(
            input_phase_space=self,
            output_phase_space=output_phase_space,
            T_matrix=T_matrix,
            K_matrix=np.eye(self.vect_dim),
            T_shift=T_shift,
            K_shift=np.zeros((self.vect_dim, 1))
        )
    
    def equals(self, other):
        return np.array_equal(self.t_vect_perp, other.t_vect_perp) and np.array_equal(self.k_vect_perp, other.k_vect_perp)
    
    def display(self):
        print("t_vect_perp")
        print(self.t_vect_perp)
        print("k_vect_perp")
        print(self.k_vect_perp)


class PhaseSpaceMap:
    def __init__(self, input_phase_space, output_phase_space, T_matrix, K_matrix, T_shift, K_shift):
        self.input_phase_space: PhaseSpace = input_phase_space
        self.output_phase_space: PhaseSpace = output_phase_space
        self.vect_dim = input_phase_space.vect_dim
        self.phase_space_dim = input_phase_space.phase_space_dim
        if(output_phase_space.vect_dim != self.vect_dim or output_phase_space.phase_space_dim != self.phase_space_dim):
            raise ValueError("Phase space dimensions do not match")
        self.T_matrix = T_matrix # shape (vect_dim, vect_dim)
        self.K_matrix = K_matrix # shape (vect_dim, vect_dim)
        self.T_shift = T_shift # shape (vect_dim, 1)
        self.K_shift = K_shift # shape (vect_dim, 1)
        self.is_length_function_set = False
        self.phase_space_list = [input_phase_space, output_phase_space]
        self.phase_space_map_list = [self]

    def is_endomorphism(self):
        return self.input_phase_space.equals(self.output_phase_space)
    
    def set_length_function_of_T(self, length_dot, length_shift):
        # should be an affine linear function of input_phase_space
        self.is_length_function_set = True
        self.length_dot = length_dot
        self.length_shift = length_shift

    def map_x(self, x):
        t_vect, k_vect = self.input_phase_space.from_phase_space_coordinates(x)
        t_vect_mapped = self.T_matrix @ t_vect + self.T_shift
        k_vect_mapped = self.K_matrix @ k_vect + self.K_shift
        return self.output_phase_space.to_phase_space_coordinates(t_vect_mapped, k_vect_mapped)
    
    def left_compose(self, after_map):
        # matrix multiplication so it is right to left, thus left is after
        composed_map = PhaseSpaceMap(
            input_phase_space=self.input_phase_space,
            output_phase_space=after_map.output_phase_space,
            T_matrix = after_map.T_matrix @ self.T_matrix,
            K_matrix = after_map.K_matrix @ self.K_matrix,
            T_shift = after_map.T_shift + after_map.T_matrix @ self.T_shift,
            K_shift = after_map.K_shift + after_map.K_matrix @ self.K_shift
        )
        composed_map.phase_space_list = self.phase_space_list[:-1].copy()
        composed_map.phase_space_list.extend(after_map.phase_space_list.copy())
        composed_map.phase_space_map_list = self.phase_space_map_list.copy()
        composed_map.phase_space_map_list.append(composed_map)
        if self.is_length_function_set and after_map.is_length_function_set:
            # Length functions are added together, so the length should be 
            # self's length_function(self.input_phase_space) + after_map's length_function(after_map.input_phase_space)
            # but we don't have access to after_map.input_phase_space
            # If after_maps's length_function(y) = cy+d
            # and y = self.T_matrix @ x + self.T_shift
            # then after_map's length function(x) = (self.T_matrix^T @ c) @ x + (c @ self.T_shift + d)
            # Thus we add (self.T_matrix^T @ c) to self.length_dot
            # and we add c @ self.T_shift + d to self.length_shift
            composed_map.length_dot = self.length_dot + self.T_matrix.T @ after_map.length_dot
            composed_map.length_shift = self.length_shift + after_map.length_dot @ self.T_shift + after_map.length_shift
        return composed_map            
    
    def right_compose(self, before_map):
        composed_map = PhaseSpaceMap(
            input_phase_space=before_map.input_phase_space,
            output_phase_space=self.output_phase_space,
            T_matrix = self.T_matrix @ before_map.T_matrix,
            K_matrix = self.K_matrix @ before_map.K_matrix,
            T_shift = self.T_shift + self.T_matrix @ before_map.T_shift,
            K_shift = self.K_shift + self.K_matrix @ before_map.K_shift
        )
        composed_map.phase_space_list = before_map.phase_space_list[:-1]
        composed_map.phase_space_list.extend(self.phase_space_list)
        composed_map.phase_space_map_list = before_map.phase_space_map_list
        composed_map.phase_space_map_list.append(composed_map)
        if self.is_length_function_set and before_map.is_length_function_set:
            composed_map.length_dot = before_map.length_dot + before_map.T_matrix.T @ self.length_dot
            composed_map.length_shift = before_map.length_shift + self.length_dot @ before_map.T_shift + self.length_shift
        return composed_map
    
    def set_map_in_phase_space_coordinates(self):
        # self is a map x -> Ax+b
        # but self is a bijection only when we consider the map between phase spaces. 
        # so x lives in input phase space and Ax+b lives in output phase space
        # so really it would be nice if we express this map using the input coordinates from input phase space
        # and the output coordinates from output phase space. 

        # n = self.input_phase_space.vect_dim        
        # so we need to change the input. The input is an n-1 dimentsional vector. Multiplying by basis and adding the offset should give us the input of A
        # To change the output, we first need to change A(x) to the output coordinates. and then we need to change b to the output coordinates.

        # for the input, a vector v in R^(n-1) maps to the vector x in R^n
        # v maps to basis @ v + offset

        # for the output, a vector x in R^n maps to the vector y in R^(n-1)
        # x maps to transition_inverse @ basis.T @ x

        after_matrix_T = self.output_phase_space.t_transition_inverse @ self.output_phase_space.t_basis.T
        after_matrix_K = self.output_phase_space.k_transition_inverse @ self.output_phase_space.k_basis.T

        # this means the matrix as a function of v would be
        # after_matrix @ A @ input_basis @ v

        # and the shift would be
        # after_matrix @ (A @ offset + b)

        self.phase_space_T_matrix = after_matrix_T @ self.T_matrix @ self.input_phase_space.t_basis
        self.phase_space_K_matrix = after_matrix_K @ self.K_matrix @ self.input_phase_space.k_basis
        self.phase_space_T_shift = after_matrix_T @ (self.T_matrix @ self.input_phase_space.t_offset + self.T_shift)
        self.phase_space_K_shift = after_matrix_K @ (self.K_matrix @ self.input_phase_space.k_offset + self.K_shift)
