import numpy as np
from scipy import optimize

# we want to find the minimum length (w.r.t. the K asymetric norm) orbit of a polytope T of no more than n+1 bounces such that 
# the cone of vectors normal to the faces of T which are hit by the orbit contains a line as a subset.

def check_if_line_in_cone(V):
    # does the cone generated by the vectors contain a line?

    # we want to find x, y such that V x = - V y (AKA V (x+y) = 0) 
    # and each component of x and y is greater than 0
    # [v_1 .. v_m] [x_1+y_1 .. x_m+y_m] = 0
    # breaking this componentwise, we get n linear equations, one for each row. Let 1 <= i <= n.
    # v_1i (x_1 + y_1) + ... + v_mi (x_m + y_m) = 0

    # This is a linear program :)

    # The function we want to optimize does not matter, WLOG, it's the sum of the components of x and y (if it's greater than 0, we return true)    
    # The constraints are:
        # x_1 >= 0 .. x_m >= 0
        # y_1 >= 0 .. y_m >= 0
        # for each row i:
        # v_1i (x_1 + y_1) + ... + v_mi (x_m + y_m) = 0

    m = V.shape[0]
    n = V.shape[1]

    # Our variables are z = [x_1, ..., x_m, y_1, ..., y_m]
    # Objective function: minimize -sum(z) (equivalent to maximizing sum(z))
    c = np.ones(2*m) * -1
    
    # Constraints: V·(x+y) = 0, which means V·z_combined = 0
    # We need to rewrite this as V_extended·z = 0
    V_extended = np.vstack([V, V])  # This creates [V | V]
    
    # Bounds: all variables > 0
    bounds = [(0, 1) for _ in range(2*m)]
    
    # Solve the linear program
    result = optimize.linprog(
        c=c,
        A_eq=V_extended.transpose(),
        b_eq=np.zeros(n),
        bounds=bounds,
        method='highs'  # Using the HiGHS solver which is more robust
    )

    # If optimization was successful and objective value is negative (meaning sum(z) is positive)
    # then we found a feasible solution
    if result.success and result.fun < -1e-8:  # Check that sum is significantly negative
        # Extract x and y from the solution
        x = result.x[:m]
        y = result.x[m:]
        
        # Verify the solution satisfies V·x = -V·y
        error = np.linalg.norm(V.transpose() @ x + V.transpose() @ y)
        if error < 1e-8:
            return True, x, y
        else:
            print("The linear program did not work as intended")
            return False, None, None
    
    # If we can't find a solution
    return False, None, None


# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [-1, -1]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1]]))) # False
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [-1, 0]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [0, -1]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [1,1], [2,4]]))) # False
