import numpy as np
from scipy import optimize
import cvxpy as cp

# we want to find the minimum length (w.r.t. the K asymetric norm) orbit of a polytope T of no more than n+1 bounces such that 
# the cone of vectors normal to the faces of T which are hit by the orbit contains a line as a subset.

def check_if_line_in_cone(V):
    # does the cone generated by the vectors contain a line?

    # we want to find x, y such that V x = - V y (AKA V (x+y) = 0) 
    # and each component of x and y is greater than 0
    # [v_1 .. v_m] [x_1+y_1 .. x_m+y_m] = 0
    # breaking this componentwise, we get n linear equations, one for each row. Let 1 <= i <= n.
    # v_1i (x_1 + y_1) + ... + v_mi (x_m + y_m) = 0

    # This is a linear program :)

    # The function we want to optimize does not matter, WLOG, it's the sum of the components of x and y (if it's greater than 0, we return true)    
    # The constraints are:
        # x_1 >= 0 .. x_m >= 0
        # y_1 >= 0 .. y_m >= 0
        # for each row i:
        # v_1i (x_1 + y_1) + ... + v_mi (x_m + y_m) = 0

    m = V.shape[0]
    n = V.shape[1]

    # Our variables are z = [x_1, ..., x_m, y_1, ..., y_m]
    # Objective function: minimize -sum(z) (equivalent to maximizing sum(z))
    c = np.ones(2*m) * -1
    
    # Constraints: V·(x+y) = 0, which means V·z_combined = 0
    # We need to rewrite this as V_extended·z = 0
    V_extended = np.vstack([V, V])  # This creates [V | V]
    
    # Bounds: all variables > 0
    bounds = [(0, 1) for _ in range(2*m)]
    
    # Solve the linear program
    result = optimize.linprog(
        c=c,
        A_eq=V_extended.transpose(),
        b_eq=np.zeros(n),
        bounds=bounds,
        method='highs'  # Using the HiGHS solver which is more robust
    )

    # If optimization was successful and objective value is negative (meaning sum(z) is positive)
    # then we found a feasible solution
    if result.success and result.fun < -1e-8:  # Check that sum is significantly negative
        # Extract x and y from the solution
        x = result.x[:m]
        y = result.x[m:]
        
        # Verify the solution satisfies V·x = -V·y
        error = np.linalg.norm(V.transpose() @ x + V.transpose() @ y)
        if error < 1e-8:
            return True, x, y
        else:
            print("The linear program did not work as intended")
            return False, None, None
    
    # If we can't find a solution
    return False, None, None

# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [-1, -1]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1]]))) # False
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [-1, 0]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [0, -1]]))) # True
# print("__")
# print(check_if_line_in_cone(np.array([[1, 0], [0, 1], [1,1], [2,4]]))) # False

# okay, for a polytope T, we need to find the face sequence of all possible orbits of length n+1 or less.
# this sucks to do, so I will do something else first.

def inner_product(vector1, vector2):
    return sum(a*b for a,b in zip(vector1, vector2))

def K_norm(p, K): # I think this is correct
    return max(inner_product(p,v) for v in K)

def K_length(pi,pi_plus1, K):
    return K_norm(pi_plus1 - pi, K) # it is not trivial why this is correct, but it is. (I proved it on paper)

# V is the list of faces hit by the orbit, and K is the norm.
def find_min_orbit(V, T, K):
    if(not check_if_line_in_cone(V)[0]):
        print("This orbit can be translated into the interior of the polytope.")
        return None
    m = V.shape[0]
    n = V.shape[1]
    # this is a convex optimization problem, so we can use cvxpy to solve it.
    # There are (n+1)*n parameters, each coorisponding to a component of a point in the orbit
    # We define the parameters as x_ij for 1 <= i <= n+1 and 1 <= j <= n, we reffer to x_i as a point in R^n
    # We want to minimize sum_i=1^n+1 K_length(x_i,x_i+1, K) + K_length(x_n+1, x_1, K)
    # The constraints are:
        # for each vector x_i, there is a vector v_j in V such that v_j . x_i = 1
        # for each vector x_i, and for each vector v_1 . x_i <= 1, ... , v_m . x_i <= 1
    
    #Define cvxpy-compatible versions of K_norm and K_length
    def cvx_K_norm(p, K):
        return cp.max(cp.hstack([p @ k_vec for k_vec in K]))    
    def cvx_K_length(pi, pi_plus1, K):
        return cvx_K_norm(pi_plus1 - pi, K)
    
    # Define variables: n+1 points in R^n
    X = [cp.Variable(n) for _ in range(n+1)]
    
    # Define binary variables to track which faces each point lies on
    is_on_face = [[cp.Variable(boolean=True) for _ in range(m)] for _ in range(n+1)]
    
    # Define slack variables to allow V[j]·X[i] to be less than 1 when not on face
    # slack[i][j] will be 0 when point i is on face j, and positive otherwise
    slack = [[cp.Variable(nonneg=True) for _ in range(m)] for _ in range(n+1)]
    
    # Define the objective: minimize the sum of K-lengths
    total_length = 0
    for i in range(n):
        total_length += cvx_K_length(X[i], X[i+1], K)
    
    # Add the length from last point back to first point
    total_length += cvx_K_length(X[n], X[0], K)
    
    # Constraints
    constraints = []
    
    epsilon = 1e-6  # Small tolerance for numerical stability

    # For each point in the orbit
    for i in range(n+1):
        # For each face
        for j in range(m):
            # This part is somewhat wrong. Cursor.AI is not good at this.
    
            constraints.append(slack[i][j] >= 0)
            
            # Connect the dot product, binary variable, and slack variable
            # V[j]·X[i] + slack[i][j] = 1
            constraints.append(V[j] @ X[i] + slack[i][j] == 1)
            
            # If is_on_face[i][j] is true, then slack[i][j] must be 0
            # If is_on_face[i][j] is false, then slack[i][j] can be positive
            # TODO: stop using big constant M
            M = 1000
            # when is_on_face[i][j] is 1, this constraint makes slack 0,
            # otherwise, it makes slack <= M, which is doing almost nothing
            constraints.append(slack[i][j] <= M * (1 - is_on_face[i][j]))
        
        # Each point must lie on at least one face
        constraints.append(cp.sum(is_on_face[i]) >= 1)
        for j in range(len(T)):
            constraints.append(T[j] @ X[i] <= 1)
    
    # Ensure that each face is used at least once
    for j in range(m):
        constraints.append(cp.sum([is_on_face[i][j] for i in range(n+1)]) >= 1)
    


    # Create and solve the problem
    prob = cp.Problem(cp.Minimize(total_length), constraints)
    
    try:
        result = prob.solve(solver=cp.MOSEK)  # Or another appropriate solver
        
        # Extract the optimal orbit
        optimal_orbit = [x.value for x in X]
        optimal_length = result
        
        # For verification, print which faces each point lies on
        for i in range(n+1):
            faces_on = [j for j in range(m) if is_on_face[i][j].value > 0.5]
            print(f"Point {i} lies on faces: {faces_on}")
            for j in range(m):
                print(f"  Face {j}: V[j]·X[i] = {np.dot(V[j], X[i].value)}, slack = {slack[i][j].value}")
            
        return optimal_orbit, optimal_length
    except Exception as e:
        print(f"Solver error: {e}")
        print("The problem may be infeasible or the solver may have encountered numerical issues.")
        return None
    

print(find_min_orbit(np.array([[0,2], [0,-2]]), np.array([[2,0], [0,2], [-2, 0], [0, -2]]), np.array([[1,0], [0,1], [-1, 0], [0, -1]])))
