import math
import time

from itertools import product
from Project.Models.Capacity import Capacity
from itertools import combinations, permutations
import cvxpy as cp
import numpy as np
import random

from Project.Services.Calculation.LengthService import K_length
from Project.Services.Calculation.OptimizeLengthLP import OptimizeLengthLP, calculate_b_length, calculate_c_length
from Project.Services.Calculation.GurobiSolver import gurobi_solver

def get_capacity(T, K, volume_k_metric, stop_num=0):
    dim = T.dim
    orbits, facet_list = get_all_untranslatable_orbits(T)
    cones_for_facet_pair = find_cones_for_facet_pair(facet_list=facet_list, T=T, K=K)
    laziness = 0
    As = []
    for orbit in orbits:
        orbit_As, b, c = get_lps_for_orbit(orbit, T, K, facet_list, cones_for_facet_pair, laziness)
        As.extend(orbit_As)
    xs, cap = gurobi_solver(As, b, c, dim, stop_num)
    return Capacity(length=cap, orbit=None, cones=None, trajectory=None)


# See OEIS A049606
def get_cube_capacity_ratio(dim):
    if dim < 2 or dim > 8:
        raise Exception("Not implemented")
    return math.factorial(dim)


def get_all_untranslatable_orbits(T):
    # all_facets = get_all_facets(T)
    all_facets = [ [v] for v in T.normal_vectors]
    all_orbits = list(combinations(all_facets, T.dim + 1))
    untranslatable_orbits = []
    facets_included = []
    for orbit in all_orbits:
        if does_orbit_support_another_orbit(orbit, untranslatable_orbits):
            continue
        vects_in_orbit = get_unique_vectors_from_orbit(orbit)
        # if vects_in_orbit is a line but a subset of it is as well, then it is inefficient to include it.
        if not is_line_in_cone(np.array(vects_in_orbit)):
            continue
        append_orbit_permutations_that_fix_last_element(orbit, untranslatable_orbits)
        # check if we can add to facets_included
        for facet in orbit:  # adding new facet to facets_included
            if all(not facets_equal(facet, included_facet) for included_facet in facets_included):
                facets_included.append(facet)
    # print("ORBITS: ", len(untranslatable_orbits))
    # print(untranslatable_orbits)
    # print("________________________________________________________________________________")
    return untranslatable_orbits, facets_included


def append_orbit_permutations_that_fix_last_element(orbit, untranslatable_orbits):
    last_element = orbit[-1]
    untranslatable_orbits.extend(prefix + (last_element,) for prefix in permutations(orbit[:-1]))


def get_unique_vectors_from_orbit(orbit):
    return list({tuple(v): v for facet in orbit for v in facet}.values())


def does_orbit_support_another_orbit(orbit, rv):
    return any(does_orbit_support_orbit(other_orbit, orbit) for other_orbit in rv)


def get_all_facets(T):
    # returns all facets of any number of dimetions of T.
    rv = []
    power_set_T = []
    for r in range(1, len(T.normal_vectors) + 1):
        power_set_T.extend(list(combinations(T.normal_vectors, r)))
    for s in power_set_T:
        try:
            if is_facet_valid(s, T):
                rv.append(s)
        except Exception as e:
            # it would bad if an error caused the program to overcredit a species.
            print("Error")
            print(T.normal_vectors)
            rv.append(s)
            raise e
    return rv


def is_facet_valid(facet, T, verbose=False):
    # return true iff there is some x in R^dim such that <x,v>=1 for all v in facet and <x,u> <= 1 for all u in T.
    x = cp.Variable(T.dim)
    constraints = [x @ v == 1 if any(np.array_equal(u, v) for u in facet) else x @ v <= 1 for v in T.normal_vectors]
    prob = cp.Problem(cp.Minimize(cp.norm(x)), constraints)
    prob.solve()
    verbose and print(prob.status, prob.status == cp.OPTIMAL)
    return prob.status == cp.OPTIMAL


# We say an orbit D supports an orbit C if for every facet S in C there is a facet S' in D such that S \subseteq S'
def does_orbit_support_orbit(orbit, support_orbit):
    return all(
        any(is_S_a_subset_of_S_prime(S, S_prime) for S_prime in support_orbit)
        for S in orbit
    )


def is_S_a_subset_of_S_prime(S, S_prime):
    return all(any(np.array_equal(vec1, vec2) for vec2 in S_prime) for vec1 in S)


def is_line_in_cone(V, epsilon=0.000001):
    # # first compute the cone and dual cone generated by V
    # # then return true if the interior of the dual cone is empty.
    # V = np.array(V)
    # k, n = V.shape

    # y = cp.Variable(n)
    # constraints = [V @ y >= epsilon]

    # prob = cp.Problem(cp.Minimize(cp.norm(y)), constraints)
    # prob.solve()

    # return prob.status != cp.OPTIMAL

    # first compute the cone and dual cone generated by V
    # then return true if the interior of the dual cone is empty.
    A = -np.array(V)
    b = np.array([-epsilon for _ in range(len(A))])

    # Not feasible means we return true
    rv = not gurobi_feasability(A, b)

    return rv


def get_lps_for_orbit(orbit, T, K, facet_list, cones_for_facet_pair, laziness=0):
    possible_cones = []
    for i, cur_facet in enumerate(orbit):
        past_facet = orbit[(i - 1) % len(orbit)]
        # find facet in facet_list
        cur_index = None
        past_index = None
        for j, facet_in_list in enumerate(facet_list):
            if facets_equal(cur_facet, facet_in_list):
                cur_index = j
            if facets_equal(past_facet, facet_in_list):
                past_index = j
        if cur_index is None or past_index is None:
            raise Exception("Facet not found in facet_list")
        possible_cones.append(cones_for_facet_pair[past_index][cur_index])

    all_cones = list(product(*possible_cones))

    if not all_cones:
        raise Exception("Unimplemented. all_cones is empty. This might be due to repeating edges")

    # print(f"We need to solve {len(all_cones)} linear programs of shape {calculate_b_length(T.dim, T, K)} by {calculate_c_length(T.dim)}")

    As = []
    b = []
    c = []

    some_cones = all_cones
    if laziness > 0:
        some_cones = random.sample(all_cones, int(len(all_cones) * laziness))

    for cones in some_cones:
        lp = OptimizeLengthLP(orbit, cones, T, K)
        if len(b) == 0:
            b = lp.b
            c = lp.c
        As.append(lp.A)

    return As, b, c

# a cone should be an array of m vectors.
def get_all_cones_of_length_n(polytope, n):
    vects = polytope.normal_vectors
    return [np.array(p, dtype=vects.dtype) for p in product(vects, repeat=n)]


def maximize_one_segment(T, K, facet_1, facet_2, cone):
    # the point on facet_1
    x1 = cp.Variable(K.dim)
    # the point on facet_2
    x2 = cp.Variable(K.dim)

    # Objective: maximize the length of the segment from x1 to x2
    diff = x2 - x1
    objective = cp.Variable()
    constraints = []

    # we want to minimize objective, but objective has three restrictions
    # 0. The definition: Objective = diff @ cone
    constraints.append(diff @ cone == objective)

    # 1. x1 must lie on facet_1 and x2 must lie on facet_2
    for v in T.normal_vectors:
        if any(np.array_equal(v, e) for e in facet_1):
            constraints.append(x1 @ v == 1)
        else:
            constraints.append(x1 @ v <= 1)
        if any(np.array_equal(v, e) for e in facet_2):
            constraints.append(x2 @ v == 1)
        else:
            constraints.append(x2 @ v <= 1)

    #2. diff must lie in cone
    for k in K.normal_vectors:
        constraints.append(diff @ cone >= diff @ k)

    prob = cp.Problem(cp.Maximize(objective), constraints)
    prob.solve()

    if prob.status == 'optimal':
        return objective.value
    else:
        return 0


def find_cones_for_facet_pair(facet_list, T, K):
    # returns a 2d array of lists of cones
    # the ith row and jth column is the list of cones that are between the ith and jth facet.
    rv = []
    for i in range(len(facet_list)):
        to_add = []
        for j in range(len(facet_list)):
            if i != j:
                cones = []
                for cone in K.normal_vectors:
                    try:
                        max_length = maximize_one_segment(T=T, K=K, facet_1=facet_list[i], facet_2=facet_list[j],
                                                          cone=cone)
                    except:
                        continue
                    epsilon = 1e-6
                    if max_length >= epsilon:
                        cones.append(cone)
                to_add.append(cones)
            else:
                to_add.append([])
        rv.append(to_add)
    return rv


def facets_equal(facet_1, facet_2):
    if len(facet_1) != len(facet_2):
        return False
    for i, u in enumerate(facet_1):
        if not np.array_equal(u, facet_2[i]):
            return False
    return True
